import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { loadAgent, loadAllAgents } from '../src/agents';
import { MAX_SLUG_CHARS as DESIGN_SLUG_CHARS } from '../src/workflows/design-loop';
import { MAX_SLUG_CHARS as TEST_SLUG_CHARS } from '../src/workflows/test-feature';
import { renderAgent, sync, yamlScalar } from './sync-claude';

const REPO_ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const CLAUDE_DIR = path.join(REPO_ROOT, '.claude');
const MARKER = 'GENERATED by scripts/sync-claude.ts';

/** Frontmatter of a generated file, as Claude Code sees it: `---` must be line 1. */
function frontmatter(text: string): Record<string, string> {
  const lines = text.split('\n');
  expect(lines[0]).toBe('---');
  const out: Record<string, string> = {};
  for (const line of lines.slice(1)) {
    if (line === '---') return out;
    if (line.startsWith('#')) continue;
    const at = line.indexOf(':');
    if (at > 0) out[line.slice(0, at)] = line.slice(at + 1).trim();
  }
  throw new Error('unterminated frontmatter');
}

describe('yamlScalar', () => {
  it('leaves an unambiguous description plain', () => {
    expect(yamlScalar('Reviews a diff; read-only.')).toBe('Reviews a diff; read-only.');
  });

  it('quotes values YAML would read as something else', () => {
    expect(yamlScalar('[base-branch]')).toBe('"[base-branch]"');
    expect(yamlScalar('note: careful')).toBe('"note: careful"');
    expect(yamlScalar('"quoted" at the start')).toBe('"\\"quoted\\" at the start"');
  });

  it('leaves a quote inside a plain scalar alone — YAML only cares about the first character', () => {
    expect(yamlScalar('say "hi"')).toBe('say "hi"');
  });
});

describe('renderAgent', () => {
  it('opens with the frontmatter delimiter and carries the marker inside it', () => {
    // A file starting with anything else (an HTML comment included) is ignored by the harness.
    const text = renderAgent(loadAgent('code-reviewer'));
    expect(text.startsWith('---\n')).toBe(true);
    expect(text.split('\n')[1]).toContain(MARKER);
  });

  it('copies name and description from agents/*.md', () => {
    const agent = loadAgent('qa-tester');
    const fm = frontmatter(renderAgent(agent));
    expect(fm.name).toBe('qa-tester');
    expect(fm.description).toBe(agent.description);
  });

  it('reproduces the agent prompt and the guardrails verbatim', () => {
    const agent = loadAgent('ui-designer');
    const text = renderAgent(agent);
    expect(text).toContain(agent.system.trim());
    expect(text).toContain('Never run `git push`');
  });

  it('grants the reviewer no way to change anything', () => {
    const tools = frontmatter(renderAgent(loadAgent('code-reviewer')))
      .tools!.split(',')
      .map((t) => t.trim());
    expect(tools).toEqual(['Read', 'Grep', 'Glob']);
    // `Bash(git diff:*)` in a subagent's `tools:` grants the plain, unrestricted Bash tool,
    // so the read-only profile can only be held by granting no Bash at all.
    for (const forbidden of ['Edit', 'Write', 'Bash', 'WebFetch', 'NotebookEdit']) {
      expect(tools.some((t) => t.startsWith(forbidden))).toBe(false);
    }
  });

  it('gives the browser-driving agents the Playwright MCP tools', () => {
    for (const name of ['qa-tester', 'ui-designer'] as const) {
      const tools = frontmatter(renderAgent(loadAgent(name))).tools!;
      expect(tools).toContain('mcp__playwright__browser_take_screenshot');
      expect(tools).toContain('Bash');
    }
    expect(frontmatter(renderAgent(loadAgent('ui-designer'))).tools).toContain('Write');
    // SPEC § Tools gives the tester write_file/edit_file under test-reports/tmp/. The harness
    // has no path scoping, so the profile carries Write (throwaway files) and withholds Edit —
    // the tester never changes an existing file. Both halves are asserted: the note in
    // NATIVE_NOTES.tester promised Write/Edit while the frontmatter granted neither.
    const testerTools = frontmatter(renderAgent(loadAgent('qa-tester')))
      .tools!.split(',')
      .map((t) => t.trim());
    expect(testerTools).toContain('Write');
    expect(testerTools).not.toContain('Edit');
    expect(renderAgent(loadAgent('qa-tester'))).not.toContain('edit_file');
  });
});

describe('the generated .claude/ tree', () => {
  const agentFiles = loadAllAgents().map((a) => path.join(CLAUDE_DIR, 'agents', `${a.name}.md`));
  const commandFiles = ['design-loop', 'review', 'test-feature'].map((n) =>
    path.join(CLAUDE_DIR, 'commands', `${n}.md`),
  );

  it('is checked in, one file per agent and per command', () => {
    for (const file of [...agentFiles, ...commandFiles]) {
      expect(fs.existsSync(file), `${path.relative(REPO_ROOT, file)} is missing`).toBe(true);
    }
  });

  it('marks every file as generated, inside the frontmatter', () => {
    for (const file of [...agentFiles, ...commandFiles]) {
      const lines = fs.readFileSync(file, 'utf8').split('\n');
      expect(lines[0], file).toBe('---');
      expect(lines[1], file).toContain(MARKER);
    }
  });

  it('gives every command a description and an argument hint', () => {
    for (const file of commandFiles) {
      const fm = frontmatter(fs.readFileSync(file, 'utf8'));
      expect(fm.description, file).toBeTruthy();
      expect(fm['argument-hint'], file).toBeTruthy();
    }
  });

  it('keeps /review headless-safe and read-only', () => {
    const text = fs.readFileSync(path.join(CLAUDE_DIR, 'commands', 'review.md'), 'utf8');
    const allowed = frontmatter(text)['allowed-tools']!;
    expect(allowed).not.toMatch(/\b(Edit|Write)\b/);
    expect(allowed).not.toMatch(/Bash\((?!git (diff|log|status|rev-parse|merge-base|branch))/);
    expect(text).toContain('never ask a question');
  });

  it('encodes the conventions the workflows actually use', () => {
    const design = fs.readFileSync(path.join(CLAUDE_DIR, 'commands', 'design-loop.md'), 'utf8');
    expect(design).toContain('screenshots/<slug>/<screen>-<viewport>.png');
    expect(design).toContain('design-loop(<slug>): checkpoint');
    expect(design).toContain('STOPPING FOR FEEDBACK');
    expect(design).toMatch(/NEVER `git push`/);

    const test = fs.readFileSync(path.join(CLAUDE_DIR, 'commands', 'test-feature.md'), 'utf8');
    expect(test).toContain('test-reports/<slug>-<date>.md');
    expect(test).toContain('app.stagingUrl');
    expect(test).toContain('test-reports/tmp/screenshots/<screen>-<viewport>.png');

    // The slug caps are the CLI's own constants. Hand-written numbers had drifted to 40, so the
    // two run paths named the same run's report and screenshot directory differently.
    expect(test).toContain(`(\u2264 ${TEST_SLUG_CHARS} chars)`);
    expect(design).toContain(`(\u2264 ${DESIGN_SLUG_CHARS} chars)`);
    for (const file of [design, test]) expect(file).not.toContain('\u2264 40 chars');

    // The unreachable-target branch must promise what src/workflows/test-feature.ts does: no
    // report when an app we started never boots, FAIL cases when there was no start command.
    expect(test).toContain('No report: an app that will not boot is not a test result.');
    expect(test).toContain('mark the cases FAIL, then');

    for (const file of [design, test]) {
      expect(file).toContain('claude mcp add playwright -- npx @playwright/mcp@latest');
    }
  });

  it('is in sync with agents/*.md', () => {
    // Same assertion as `npm run sync-claude -- --check`: regenerating changes nothing.
    expect(sync(true).clean).toBe(true);
  });
});
