/**
 * T11 — generate the Claude Code native layer (`.claude/`) from `agents/*.md`.
 *
 * `agents/` is the single source for every agent prompt: this script only maps each agent's
 * permission profile onto Claude Code tool names and wraps the prompt in the frontmatter the
 * harness expects. Nothing here restates a prompt that already lives in `agents/`.
 *
 * Output is deterministic — fixed key order, fixed file order, no timestamps — so running it
 * twice leaves `git status` clean. Files are only written when their content actually changes.
 *
 * Usage:
 *   npx tsx scripts/sync-claude.ts          # write `.claude/`
 *   npx tsx scripts/sync-claude.ts --check  # exit 1 if anything would change (CI / T12)
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadAllAgents, type Agent, type AgentProfile } from '../src/agents';
// The command bodies quote the artifact-name limits the CLI actually applies. Importing them
// is what keeps the two run paths from naming the same run's report and screenshot directory
// differently (the numbers used to be hand-written here, and had drifted to 40).
import { MAX_SLUG_CHARS as DESIGN_SLUG_CHARS } from '../src/workflows/design-loop';
import { MAX_SLUG_CHARS as TEST_SLUG_CHARS } from '../src/workflows/test-feature';

const here = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.join(here, '..');
const CLAUDE_DIR = path.join(REPO_ROOT, '.claude');

/**
 * Marker identifying a generated file. It sits INSIDE the frontmatter, as its first line:
 * Claude Code parses `.claude/**.md` with the YAML delimiter expected at line 1, and a file
 * that starts with an HTML comment is silently ignored (verified against this machine's
 * Claude Code build — see tasks/T11.md § Deviations).
 */
const MARKER = 'GENERATED by scripts/sync-claude.ts';
/** Agent prompts really do come from `agents/*.md`. */
const AGENT_MARKER = `${MARKER} — edit agents/*.md instead`;
/** Command bodies do not: they are string constants in this script. */
const COMMAND_MARKER = `${MARKER} — edit scripts/sync-claude.ts instead`;

/**
 * Playwright MCP tools (`claude mcp add playwright -- npx @playwright/mcp@latest`), listed in
 * a fixed order. Unknown tool names in `tools:` are ignored by the harness, so naming them
 * here is safe on a machine where the server is not installed yet.
 */
const PLAYWRIGHT_TOOLS = [
  'mcp__playwright__browser_navigate',
  'mcp__playwright__browser_navigate_back',
  'mcp__playwright__browser_resize',
  'mcp__playwright__browser_snapshot',
  'mcp__playwright__browser_take_screenshot',
  'mcp__playwright__browser_click',
  'mcp__playwright__browser_type',
  'mcp__playwright__browser_fill_form',
  'mcp__playwright__browser_hover',
  'mcp__playwright__browser_select_option',
  'mcp__playwright__browser_press_key',
  'mcp__playwright__browser_wait_for',
  'mcp__playwright__browser_console_messages',
  'mcp__playwright__browser_network_requests',
  'mcp__playwright__browser_close',
] as const;

/**
 * SPEC § Tools and permission profiles, expressed in Claude Code tool names.
 *
 * The reviewer gets NO Bash: in a subagent's `tools:` list a scoped entry such as
 * `Bash(git diff:*)` is not an allow-list — the harness grants the plain `Bash` tool, i.e. an
 * unrestricted shell, which the read-only reviewer profile forbids. The reviewer is handed the
 * diff in its prompt by `/review` instead (tasks/T11.md § Deviations).
 */
const PROFILE_TOOLS: Record<AgentProfile, readonly string[]> = {
  reviewer: ['Read', 'Grep', 'Glob'],
  tester: ['Read', 'Grep', 'Glob', 'Bash', 'Write', 'WebFetch', ...PLAYWRIGHT_TOOLS],
  designer: ['Read', 'Edit', 'Write', 'Grep', 'Glob', 'Bash', ...PLAYWRIGHT_TOOLS],
};

/**
 * Per-profile bridge between the prompt's CLI tool names (`browser_screenshot`, `http_request`,
 * …) and the tools a Claude Code subagent actually has. Appended after the shared prompt; it
 * adds no instructions that `agents/*.md` already carries.
 */
const NATIVE_NOTES: Record<AgentProfile, string> = {
  reviewer: [
    'TOOLS IN THIS SESSION (Claude Code):',
    '- you have Read, Grep and Glob only — no shell, no editing, no network;',
    '- the diff and the changed-file list arrive in your prompt; read surrounding context with',
    '  Read/Grep before judging, and never ask for more input.',
  ].join('\n'),
  tester: [
    'TOOLS IN THIS SESSION (Claude Code):',
    '- `http_request` → run the call with Bash (`curl -i …`) or WebFetch; quote the exact request',
    '  and the exact response into the report;',
    '- `browser_*` → the Playwright MCP tools (`mcp__playwright__browser_navigate`,',
    '  `mcp__playwright__browser_click`, `mcp__playwright__browser_fill_form`,',
    '  `mcp__playwright__browser_take_screenshot`, `mcp__playwright__browser_console_messages`).',
    '  Screenshots are saved as `test-reports/tmp/screenshots/<screen>-<viewport>.png`.',
    '  If those tools are absent, stop and say the Playwright MCP server is missing;',
    '- `write_file` → Write, under `test-reports/tmp/` only. There is no Edit in this session:',
    '  the tester creates throwaway files, it never changes an existing one;',
    '- never start, restart or stop the app, and never run a long-running command.',
  ].join('\n'),
  designer: [
    'TOOLS IN THIS SESSION (Claude Code):',
    '- `write_file`/`edit_file` → Write/Edit; the dev server hot-reloads, so there is no build step;',
    '- `browser_goto` → `mcp__playwright__browser_navigate`;',
    '  `browser_click` → `mcp__playwright__browser_click`;',
    '  `browser_fill` → `mcp__playwright__browser_type` / `mcp__playwright__browser_fill_form`;',
    '  `browser_console_errors` → `mcp__playwright__browser_console_messages`;',
    '  viewports → `mcp__playwright__browser_resize` before each screenshot;',
    '  `browser_screenshot` → `mcp__playwright__browser_take_screenshot`, saved as',
    '  `screenshots/<slug>/<screen>-<viewport>.png` (the slug is given to you in the prompt).',
    '  If those tools are absent, stop and say the Playwright MCP server is missing;',
    '- never start, restart or stop a server: the app is already running;',
    '- never run `git add`, `git commit` or `git push` — the command makes the checkpoint commit.',
  ].join('\n'),
};

interface CommandSpec {
  /** File name without `.md`; also the slash command name. */
  name: string;
  description: string;
  argumentHint: string;
  /** Optional permission allow-list (Claude Code command frontmatter). */
  allowedTools?: readonly string[];
  body: string;
}

const PLAYWRIGHT_REQUIRED = [
  'PLAYWRIGHT MCP IS REQUIRED for every browser step. Before the first one, check that the',
  '`mcp__playwright__browser_*` tools are available. If they are not, STOP and tell the developer',
  'to run `claude mcp add playwright -- npx @playwright/mcp@latest` and restart Claude Code',
  '(docs/HANDOFF.md Step 1). Never substitute curl, a headless script or a described screenshot',
  'for a real browser check.',
].join('\n');

const REVIEW_BODY = `Review the current branch against \`\${1:-main}\` and print the verdict as plain text.

This command must work headless (\`claude -p "/review"\`): never ask a question, never wait for
input, never edit, commit or push anything. It needs no browser tools — only /design-loop and
/test-feature require the Playwright MCP server.

1. Resolve the base ref \`\${1:-main}\` with \`git rev-parse --verify "\${1:-main}^{commit}"\`. If it
   does not exist locally, try \`origin/\${1:-main}\` once and say which ref you used. If neither
   resolves, print \`unknown base ref "\${1:-main}"\` and stop.
2. \`git diff --name-only \${1:-main}...HEAD\` for the changed files, then
   \`git diff \${1:-main}...HEAD\` for the diff. Three dots, always — the merge-base diff, not the
   two-dot one. If the diff is empty, print exactly \`nothing to review\`, nothing else, and stop:
   no explanation of why it is empty, no offer to review the working tree instead.
3. Cap what you hand over at ~60 KB: include whole per-file diffs while they fit, then a head
   slice of the first file that does not, and name the files that were cut short or left out so
   the reviewer knows to read them itself.
4. Delegate the judgement to the **code-reviewer** subagent (one Task call). Give it: the repo
   root, the base ref, the changed-file list, which files are truncated or omitted, and the diff.
   The subagent is read-only (Read/Grep/Glob) — it reads surrounding context itself. Do not
   review the diff yourself and do not soften what it reports.
5. Print the reviewer's answer verbatim, in this exact shape, nothing before the VERDICT line —
   no preamble, no summary, no markdown headings, no code fences:

\`\`\`
VERDICT: <APPROVE | APPROVE WITH NITS | REQUEST CHANGES>

[SEVERITY] path/to/file.ts:LINE — one-line title
Risk: why this matters in practice.
Fix: concrete change.
\`\`\`

   Severity is one of BLOCKER, MAJOR, MINOR, NIT; findings are sorted BLOCKER first; the
   separator between \`file:line\` and the title is an em dash ("—"), not a hyphen; every finding
   is exactly three lines. \`REQUEST CHANGES\` requires at least one finding in that format.
   With no findings, print only the VERDICT line.
6. If the answer does not match that format, ask the subagent exactly once more, appending
   \`Your previous output violated the format. Output only the required format.\` If the retry is
   still malformed, print one line saying so followed by the raw text — never invent a verdict.
7. A BLOCKER is reported in the text (the agent-workflows CLI, \`aw review\`, maps it to exit
   code 2; a slash command cannot set an exit code). Never fix the code here and never ask questions —
   this command reviews, the human decides.

The last line you print is either \`nothing to review\` or the last \`Fix:\` line. Never close with
a question, an offer, a next step or a summary: under \`claude -p\` there is nobody to answer.`;

const TEST_FEATURE_BODY = `Black-box test \`$1\` against a running app and write a findings report. Verify only — never fix
the code, and never present a fix as done.

Arguments: \`$1\` is the feature or bug report to verify; \`$2\` is an optional base URL.
Read \`./aw.config.json\` for the rest (\`app.baseUrl\`, \`app.backend\`, \`app.testAccount\`,
\`app.stagingUrl\`, \`offLimits\`). If \`$1\` is empty, stop and ask for a description — that is the
only question this command may ask.

${PLAYWRIGHT_REQUIRED}

1. **Target.** \`$2\` if given, else \`app.baseUrl\`, else \`http://localhost:<app.backend.port>\`.
   If none of those exist, stop with \`no target: pass a base URL or configure app.baseUrl\`.
2. **Safety.** If the target is not localhost/127.0.0.1 it MUST equal \`app.stagingUrl\` exactly —
   otherwise stop and print both values. Never touch production, not even with a probe.
   POST/PUT/PATCH/DELETE against a non-local target need the developer's explicit confirmation in
   this session before you send them; against localhost they are allowed. Respect \`offLimits\`.
3. **Reachability.** Probe \`<target><app.backend.healthPath ?? "/">\` (5 s). If it is down and
   \`app.backend.start\` is configured for that same host and port, start it in the background from
   the repo root, poll every 2 s for up to 60 s, and stop it again when the run ends. Then the two
   cases part company, exactly as the CLI does:
   - you started it and it never answered — stop there with the command you tried, the repo root
     and the last error. No report: an app that will not boot is not a test result.
   - there was no start command for that host and port — test the target as given. The refused
     connections ARE the result: record each exact failed request and mark the cases FAIL, then
     go on to step 6 and write the report.
   Either way, do not hunt for the app on another port and do not test any other address.
4. **Plan and execute.** Delegate to the **qa-tester** subagent (Task). Give it the description,
   the target, whether destructive methods are permitted, the test-account user and the env var
   holding the password (never the password itself), and \`offLimits\`. It must first write a plan
   covering happy path, edge cases, invalid input and authn/authz — for a bug report, the exact
   repro steps — then run every case with a real call before grading it. Throwaway files go under
   \`test-reports/tmp/\` only (screenshots as
   \`test-reports/tmp/screenshots/<screen>-<viewport>.png\`); application source is never modified.
5. **Collect.** Every case comes back as \`{ id, name, kind (happy|edge|invalid|auth),
   status (PASS|FAIL|SKIP), request, response, reproSteps?, severity? }\`. \`request\` and \`response\`
   are mandatory for every FAIL and must be the literal text that was seen; \`severity\`
   (BLOCKER|MAJOR|MINOR|NIT) is for FAIL cases only. If the answer is unusable, ask once more for
   the case list alone — no second full run.
6. **Report.** Write \`test-reports/<slug>-<date>.md\`, where \`<slug>\` is the description
   lowercased and hyphenated (≤ ${TEST_SLUG_CHARS} chars) and \`<date>\` is today in local time
   as \`YYYY-MM-DD\`.
   Never overwrite an existing report — append \`-2\`, \`-3\`, … Sections, in order:
   a title line \`# Test report — <description>\`; a bullet list with **Target**, **Agent**,
   **Run at** (ISO 8601) and the PASS/FAIL/SKIP counts, plus **App started by this run** when you
   started it; \`## Test plan\`; \`## Cases\` with one \`### <n>. <name> — <STATUS>\` block per case
   (id, kind, severity, fenced Request, fenced Response, repro steps); \`## Summary\` (≤ 3 lines).
7. **Present.** Print the report path, then the ≤ 3-line summary, then \`PASS <passed>/<total>\`.
   Failing cases are findings, not a broken run. Stop there and wait for the developer.`;

const DESIGN_LOOP_BODY = `Implement the UI for \`$1\`, verify it in a real browser, screenshot both viewports, checkpoint the
work, then stop for feedback.

\`$1\` is either a feature description or the path to a spec file — if it names an existing file,
read that file and use its contents as the spec. Read \`./aw.config.json\` for \`app.frontend\`,
\`app.baseUrl\`, \`viewports\` and \`offLimits\`. If \`$1\` is empty, stop and ask what to build — that
is the only question this command may ask.

${PLAYWRIGHT_REQUIRED}

1. **Slug.** \`<slug>\` = the first 6 words of the feature, lowercased and hyphenated
   (≤ ${DESIGN_SLUG_CHARS} chars).
   Every screenshot for this run goes under \`screenshots/<slug>/\`.
2. **App.** The frontend must be running at \`http://localhost:<app.frontend.port>\` (or
   \`app.baseUrl\`). If it is not, start \`app.frontend.start\` (and \`app.backend.start\` when
   configured) in the background from the repo root, wait until it answers, and stop whatever you
   started when the run ends. Never leave a server or a watcher behind.
3. **Plan.** Read the backend contract first — the routes, payloads and auth the screens depend
   on — then print a plan of at most 5 short lines (screens, components, states). No preamble,
   no code, no headings.
4. **Implement.** Delegate to the **ui-designer** subagent (Task) with: the plan, the feature or
   spec, the frontend URL, the backend base URL, the repo root, \`screenshots/<slug>/\`, the
   viewports, and \`offLimits\`. It edits files with Write/Edit; it never starts or stops a server,
   never runs \`git add\`/\`git commit\`/\`git push\`, and never asks questions — an open product
   decision is resolved the way the existing app resolves it and recorded as a judgment call.
5. **Verify in the browser.** For every touched screen, at BOTH viewports (mobile
   \`viewports.mobile\`, default 375x812; desktop \`viewports.desktop\`, default 1440x900):
   \`browser_resize\` → \`browser_navigate\` → exercise the interactive states (hover, click, submit,
   loading, error, empty) → \`browser_console_messages\` must come back clean →
   \`browser_take_screenshot\` saved as \`screenshots/<slug>/<screen>-<viewport>.png\` (e.g.
   \`screenshots/user-profile-page/settings-mobile.png\`). Fix and re-check until console errors
   are gone, both viewports render correctly and the screen matches the rest of the app.
   At least one screenshot per touched screen per viewport is MANDATORY: with no screenshot the
   work counts as unfinished — say so and stop rather than presenting it.
6. **Checkpoint.** \`git add -A && git commit -m "design-loop(<slug>): checkpoint"\` from the repo
   root. If the tree is clean, skip it and say nothing was committed. **NEVER \`git push\`**, never
   open or comment on a PR, never amend or rebase — the checkpoint is a local safety net and the
   human decides what leaves the machine.
7. **Present and STOP.** Print three blocks and nothing else after them:
   \`CHANGED FILES:\` (one per line, from the checkpoint), \`SCREENSHOTS:\` (every path saved this
   run), \`JUDGMENT CALLS:\` (one bullet each, or \`(none reported)\`). Then print this line exactly:

\`\`\`
--- STOPPING FOR FEEDBACK — resume with: aw design-loop "$1" --iterate "<your feedback>" ---
\`\`\`

   \`$1\` is substituted for real: print the feature you were given, so the line can be copied
   and run as it stands.

   Inside this session the developer can also just reply with the feedback. On feedback, apply it
   to the existing implementation and re-run steps 5–7 for the AFFECTED SCREENS ONLY — do not
   rebuild what was already approved, and do not re-screenshot untouched screens.`;

const COMMANDS: readonly CommandSpec[] = [
  {
    name: 'design-loop',
    description:
      "Implement a feature's UI, verify it in a real browser, screenshot both viewports, checkpoint, then stop for feedback",
    argumentHint: '<feature|spec-path>',
    body: DESIGN_LOOP_BODY,
  },
  {
    name: 'review',
    description:
      "Review the current branch's diff like a strict senior engineer and print the verdict as plain text",
    argumentHint: '[base-branch]',
    // Read-only by construction: the command must stay safe under `claude -p`, and every tool
    // it needs is either read-only or the Task call that reaches the reviewer subagent.
    allowedTools: [
      'Task',
      'Agent',
      'Read',
      'Grep',
      'Glob',
      'Bash(git diff:*)',
      'Bash(git log:*)',
      'Bash(git status:*)',
      'Bash(git rev-parse:*)',
      'Bash(git merge-base:*)',
      'Bash(git branch:*)',
    ],
    body: REVIEW_BODY,
  },
  {
    name: 'test-feature',
    description:
      'Black-box test a feature or bug report against a running app and write a findings report',
    argumentHint: '<description> [base-url]',
    body: TEST_FEATURE_BODY,
  },
];

// ---------------------------------------------------------------------------
// rendering
// ---------------------------------------------------------------------------

/**
 * Emit a YAML scalar. Plain when it is unambiguous, double-quoted otherwise — a description
 * containing `: ` or a leading indicator character would otherwise change meaning or fail to parse.
 */
export function yamlScalar(value: string): string {
  const safe =
    /^[A-Za-z0-9]/.test(value) &&
    !/: /.test(value) &&
    !/ #/.test(value) &&
    !/[\n\r\t]/.test(value) &&
    !/[:#]$/.test(value) &&
    value.trim() === value;
  if (safe) return value;
  return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, ' ')}"`;
}

/** `.claude/agents/<name>.md` — frontmatter + the agent's own prompt (body + guardrails). */
export function renderAgent(agent: Agent): string {
  const lines = [
    '---',
    `# ${AGENT_MARKER}`,
    `name: ${agent.name}`,
    `description: ${yamlScalar(agent.description)}`,
    `tools: ${PROFILE_TOOLS[agent.profile].join(', ')}`,
    '---',
    '',
    agent.system.trim(),
    '',
    NATIVE_NOTES[agent.profile],
    '',
  ];
  return lines.join('\n');
}

/** `.claude/commands/<name>.md` — frontmatter + the workflow the CLI actually implements. */
export function renderCommand(cmd: CommandSpec): string {
  const lines = ['---', `# ${COMMAND_MARKER}`, `description: ${yamlScalar(cmd.description)}`];
  lines.push(`argument-hint: ${yamlScalar(cmd.argumentHint)}`);
  if (cmd.allowedTools) lines.push(`allowed-tools: ${cmd.allowedTools.join(', ')}`);
  lines.push('---', '', cmd.body.trim(), '');
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// filesystem
// ---------------------------------------------------------------------------

type Status = 'created' | 'updated' | 'unchanged' | 'removed';

interface Change {
  file: string;
  status: Status;
}

function relative(file: string): string {
  return path.relative(REPO_ROOT, file);
}

/** Was this file produced by this script? Only such files are ever overwritten or pruned. */
function isGenerated(file: string): boolean {
  try {
    return fs.readFileSync(file, 'utf8').includes(MARKER);
  } catch {
    return false;
  }
}

function syncFile(file: string, content: string, check: boolean): Change {
  let existing: string | undefined;
  try {
    existing = fs.readFileSync(file, 'utf8');
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code !== 'ENOENT') throw err;
  }
  if (existing === content) return { file, status: 'unchanged' };
  if (existing !== undefined && !existing.includes(MARKER)) {
    throw new Error(
      `refusing to overwrite hand-written file ${relative(file)} — it carries no "${MARKER}" marker`,
    );
  }
  const status: Status = existing === undefined ? 'created' : 'updated';
  if (!check) {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, content, 'utf8');
  }
  return { file, status };
}

/** Delete generated `.md` files in `dir` that the current run did not produce. */
function prune(dir: string, keep: ReadonlySet<string>, check: boolean): Change[] {
  let entries: string[];
  try {
    entries = fs.readdirSync(dir);
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') return [];
    throw err;
  }
  const removed: Change[] = [];
  for (const entry of entries.sort()) {
    const full = path.join(dir, entry);
    if (keep.has(full) || !entry.endsWith('.md') || !fs.statSync(full).isFile()) continue;
    // A file the developer wrote by hand is theirs; only our own leftovers are pruned.
    if (!isGenerated(full)) continue;
    if (!check) fs.rmSync(full);
    removed.push({ file: full, status: 'removed' });
  }
  return removed;
}

export interface SyncResult {
  changes: Change[];
  /** True when nothing on disk had to change. */
  clean: boolean;
}

export function sync(check = false): SyncResult {
  const agentsOut = path.join(CLAUDE_DIR, 'agents');
  const commandsOut = path.join(CLAUDE_DIR, 'commands');

  const changes: Change[] = [];
  const writtenAgents = new Set<string>();
  // `loadAllAgents()` returns them in `AgentName` order — stable across runs and machines.
  for (const agent of loadAllAgents()) {
    const file = path.join(agentsOut, `${agent.name}.md`);
    writtenAgents.add(file);
    changes.push(syncFile(file, renderAgent(agent), check));
  }

  const writtenCommands = new Set<string>();
  for (const cmd of [...COMMANDS].sort((a, b) => a.name.localeCompare(b.name, 'en'))) {
    const file = path.join(commandsOut, `${cmd.name}.md`);
    writtenCommands.add(file);
    changes.push(syncFile(file, renderCommand(cmd), check));
  }

  changes.push(...prune(agentsOut, writtenAgents, check));
  changes.push(...prune(commandsOut, writtenCommands, check));

  return { changes, clean: changes.every((c) => c.status === 'unchanged') };
}

function main(argv: readonly string[]): void {
  const check = argv.includes('--check');
  const unknown = argv.filter((a) => a !== '--check');
  if (unknown.length > 0) {
    process.stderr.write(`unknown argument(s): ${unknown.join(' ')}\nusage: sync-claude [--check]\n`);
    process.exit(1);
  }

  let result: SyncResult;
  try {
    result = sync(check);
  } catch (err) {
    // AgentError (a malformed `agents/*.md`) and fs errors both land here as plain messages.
    const message = err instanceof Error ? err.message : String(err);
    process.stderr.write(`sync-claude failed: ${message}\n`);
    process.exit(1);
  }

  for (const change of result.changes) {
    process.stdout.write(`${change.status.padEnd(9)} ${relative(change.file)}\n`);
  }
  if (check && !result.clean) {
    process.stderr.write('.claude/ is out of date — run `npm run sync-claude`\n');
    process.exit(1);
  }
  process.stdout.write(result.clean ? '.claude/ is up to date\n' : '.claude/ synced\n');
}

// Only run when executed directly, so the renderers stay importable from tests.
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main(process.argv.slice(2));
}
